#e2.1drawpython.py
import turtle
turtle.setup(650,300,200,200)
turtle.penup()
turtle.fd(-250)
turtle.pencolor("green")
turtle.pendown()
turtle.pensize(25)
turtle.pencolor('blue')
turtle.seth(-40)
for i in range(4):
        turtle.circle(40,80)
        turtle.pencolor("pink")
        turtle.circle(-40,80)
        turtle.pencolor("yellow")
turtle.circle(40,80/2)
turtle.fd(40)
turtle.pencolor("red")
turtle.circle(16,180)
turtle.fd(40*2/3)        
